import { CareerProps } from '../types/careers';

export const CAREERS: CareerProps[] = [
  {
    position: 'Frontend Developer - Web3 Focus',
    company: 'International Freelance',
    company_legal_name: 'Freelance',
    logo: '',
    location: 'Remote',
    location_type: 'Remote',
    type: 'Freelance',
    start_date: '2024-01',
    end_date: null,
    industry: 'blockchain',
    link: '#',
    responsibilities: [
      'Developed DApps, presale platforms, and token sale systems using TypeScript/Next.js',
      'Built real-time trading bots, price trackers, and on-chain monitoring tools with REST API and WebSocket',
      'Implemented smart contract integrations for staking, liquidity pools, and yield farming dashboards',
      'Created interactive landing pages with Three.js and managed full project lifecycle from design to deployment',
    ],
  },
  {
    position: 'Lead Frontend Developer & Designer',
    company: 'Satori Labs',
    company_legal_name: 'Satori Labs',
    logo: '',
    location: 'Remote',
    location_type: 'Remote',
    type: 'Full-time',
    start_date: '2023-01',
    end_date: '2024-01',
    industry: 'defi',
    link: '#',
    responsibilities: [
      'Built comprehensive DeFi platform for Bitcoin ecosystem featuring staking, farming, bridge, and launchpad',
      'Developed entire frontend (Next.js/React/TypeScript) including landing pages, dashboards, and DeFi interfaces',
      'Implemented BRC-20 and ERC-20 token integrations with multi-chain wallet connections',
      'Created staking dashboard with 4 lock periods, APY calculations, and tier-based launchpad with anti-bot protection',
      'Designed all UI/UX, brand identity, and whitepaper layout using Figma/Adobe Creative Suite',
    ],
  },
  {
    position: 'Frontend Developer - Web3 & Blockchain',
    company: 'International Freelance',
    company_legal_name: 'Freelance',
    logo: '',
    location: 'Remote',
    location_type: 'Remote',
    type: 'Freelance',
    start_date: '2021-01',
    end_date: '2023-01',
    industry: 'blockchain',
    link: '#',
    responsibilities: [
      'Developed DeFi and blockchain applications using React, Next.js, and TypeScript',
      'Integrated smart contracts on Ethereum, BSC, and EVM-compatible networks (Ethers.js, Web3.js)',
      'Built DEX interfaces, yield farming dashboards, and real-time trading tools with blockchain notifications',
    ],
  },
  {
    position: 'Frontend Developer',
    company: 'International Freelance',
    company_legal_name: 'Freelance',
    logo: '',
    location: 'Remote',
    location_type: 'Remote',
    type: 'Freelance',
    start_date: '2019-01',
    end_date: '2021-01',
    industry: 'web development',
    link: '#',
    responsibilities: [
      'Developed responsive landing pages, dashboards, and web applications for international crypto and startup clients',
      'Built performant web interfaces with HTML5, CSS3, JavaScript (ES6+) and created UI/UX designs using Figma/Adobe',
    ],
  },
];
